services:

  postgres:
    image: postgres:17
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - backend-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:8
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped

    volumes:
      - redis-data:/data

    networks:
      - backend-network

    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    restart: unless-stopped

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: docker

    networks:
      - backend-network

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: [
        "CMD",
        "curl",
        "-f",
        "http://localhost:8080/actuator/health"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped

    networks:
      - backend-network

    depends_on:
      backend:
        condition: service_healthy


networks:
  backend-network:
    name: ${NETWORK_NAME}

volumes:
  postgres-data:
  redis-data: