package com.example.shopapi.auth.enums;

public enum SecurityEventType {
    REGISTER,
    EMAIL_VERIFIED,

    LOGIN,
    LOGIN_FAILED,

    LOGOUT_CURRENT,
    LOGOUT_SESSION,
    LOGOUT_ALL_EXCEPT,
    LOGOUT_ALL,

    REFRESH,

    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,

    SESSION_CREATED,
    SESSION_REVOKED,

    TOKEN_REUSE,

    SUSPICIOUS_LOGIN,
    SESSION_LIMIT_KICK,
    SESSION_TRUSTED,
    SESSION_UNTRUSTED,
    SESSION_RENAMED,

}